poupex-dojo:
#  TODO: mudar para o objeto de queue para evitar confusão
  direct-routing-key: direct-queue
  fanout-exchange: amq.fanout
  topic-exchange: amq.topic
  dead-letter-fanout-exchange: fanout.dlx
  queue:
    fanout-queue: fanout-queue
    fanout-queue-2: fanout-queue-2
    dead-letter-fanout-queue: fanout-dlq
    arquivos-topic-queue: arquivos-topic-queue
    assuntos-topic-queue: assuntos-topic-queue
    pagamentos-topic-queue: pagamentos-topic-queue
---
spring:
  application:
    name: poupex-dojo
  rabbitmq:
    port: 5672
    username: myuser
    password: secret